# Generated by Django 4.2.7 on 2026-02-26 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_sessions', '0016_add_site_and_scope_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('directory_info', 'Directory Information'), ('disclosure', 'Disclosure'), ('research', 'Research')], max_length=50)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('parent_signature', models.TextField(blank=True, null=True)),
                ('date_signed', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='academic_sessions.student')),
            ],
            options={
                'db_table': 'consent_records',
                'ordering': ['-date_signed'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('session', 'Session'), ('api', 'API'), ('report', 'Report')], max_length=50)),
                ('record_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('print', 'Print')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('legitimate_interest', models.BooleanField(default=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON of changed fields', null=True)),
                ('site', models.ForeignKey(blank=True, help_text='Site context (for report filtering).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='academic_sessions.site')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'access_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('unauthorized_access', 'Unauthorized Access'), ('data_export', 'Data Export'), ('data_deletion', 'Data Deletion'), ('account_locked', 'Account Locked'), ('mfa_failed', 'MFA Failed'), ('suspicious_activity', 'Suspicious Activity'), ('configuration_change', 'Configuration Change')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(help_text='Event details in JSON format')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='security_ev_event_t_efa0a0_idx'), models.Index(fields=['severity', 'resolved'], name='security_ev_severit_23d5a6_idx'), models.Index(fields=['user', 'timestamp'], name='security_ev_user_id_6a5f21_idx')],
            },
        ),
        migrations.CreateModel(
            name='DisclosureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclosed_to', models.CharField(help_text='Name/organization receiving disclosure', max_length=200)),
                ('purpose', models.TextField(help_text='Purpose of disclosure')),
                ('date_disclosed', models.DateTimeField(auto_now_add=True)),
                ('consent_obtained', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('consent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclosures', to='compliance.consentrecord')),
                ('site', models.ForeignKey(blank=True, help_text='Site of student (for report filtering).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disclosure_logs', to='academic_sessions.site')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='academic_sessions.student')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disclosures_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disclosure_log',
                'ordering': ['-date_disclosed'],
                'indexes': [models.Index(fields=['student', 'date_disclosed'], name='disclosure__student_eeb9b6_idx'), models.Index(fields=['user', 'date_disclosed'], name='disclosure__user_id_caa8f6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['student', 'consent_type'], name='consent_rec_student_070656_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['status'], name='consent_rec_status_30fc43_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user', 'timestamp'], name='access_log_user_id_d8f41b_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['record_type', 'record_id'], name='access_log_record__a5b004_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['action', 'timestamp'], name='access_log_action_d908ed_idx'),
        ),
    ]
