# Generated by Django 4.2.7 on 2026-02-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0002_add_concurrent_editing_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_session_683e73_idx',
            old_name='employees_session_9a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_email_f66e96_idx',
            old_name='employees_email_3d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_session_c77c6a_idx',
            old_name='students_session_8b0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_last_na_08ef26_idx',
            old_name='students_last_na_2c2e2a_idx',
        ),
        migrations.AddField(
            model_name='student',
            name='class_num',
            field=models.CharField(blank=True, help_text='Class number/identifier', max_length=20, null=True),
        ),
    ]
