# Generated by Django 4.2.7 on 2026-02-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0015_student_aide_1to1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Order in UI dropdowns')),
            ],
            options={
                'db_table': 'sites',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='employee',
            new_name='employees_session_515d2e_idx',
            old_name='employees_session_idx',
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_size',
            field=models.CharField(blank=True, help_text='Ratio e.g. 12:1:2 = 12 students, 1 teacher, 2 assistants; 8:1:2 = 8,1,2; 6:1:2 = 6,1,2. With 1:1 aides, class may exceed ratio with special approval.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, help_text='Home phone', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_num',
            field=models.CharField(blank=True, help_text='CLASSNUM from QRY_student Data Center Based; determines class/teacher/assistants on roster.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this session belongs to; required for multi-site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic_sessions.site'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('site', 'name'), name='academic_sessions_site_name_uniq'),
        ),
    ]
