# Generated by Django 4.2.7 on 2026-03-02 14:37

from django.db import migrations, models
import django.db.models.deletion


def backfill_student_service_type_and_active(apps, schema_editor):
    Student = apps.get_model('academic_sessions', 'Student')
    for s in Student.objects.all():
        if (s.class_num or '').strip():
            s.service_type = 'center_based'
        else:
            s.service_type = 'related_service'
        s.is_active = (s.status == 'active')
        s.save(update_fields=['service_type', 'is_active'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0017_seed_sites_and_assign_rockland'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('reason_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reason_label', models.CharField(max_length=200)),
                ('billable_flag', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'absence_reasons',
                'ordering': ['reason_label'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20)),
                ('late_arrival_time', models.TimeField(blank=True, null=True)),
                ('early_dismissal_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date', 'student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('student_name_freeform', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('incident_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('reported_by', models.CharField(blank=True, max_length=200, null=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notified_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-incident_date', '-incident_time', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name', 'date_of_birth']},
        ),
        migrations.RemoveConstraint(
            model_name='academicsession',
            name='academic_sessions_site_name_uniq',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='discharge_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(blank=True, help_text='District (display label).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='Student/parent email (display as Email).', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_cell',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='home_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False when discharged; keeps discharge info.'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_end_date',
            field=models.DateField(blank=True, help_text='Medical clearance end; used for due/overdue reports.', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_cell',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='service_type',
            field=models.CharField(blank=True, choices=[('center_based', 'Center-based'), ('related_service', 'Related service')], default='center_based', help_text='Center-based = has class; Related service = no class.', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='sped_indiv_code',
            field=models.CharField(blank=True, help_text='SPED INDIV Code.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='vaccines_last_reviewed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='vaccines_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='vaccines_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='site',
            field=models.ForeignKey(help_text='Site this session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic_sessions.site'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_due_date',
            field=models.DateField(blank=True, help_text='Legacy: next medical due.', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_district',
            field=models.CharField(blank=True, help_text='School district from Access (legacy).', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name', 'date_of_birth'], name='students_roster_name_dob_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['session', 'is_active'], name='students_session_19c026_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['session', 'service_type'], name='students_session_df7349_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='academic_sessions_site_name_uniq'),
        ),
        migrations.AddField(
            model_name='incident',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Optional: scope by session.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='academic_sessions.academicsession'),
        ),
        migrations.AddField(
            model_name='incident',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='academic_sessions.student'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='absence_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academic_sessions.absencereason'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academic_sessions.student'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('date', 'student'), name='attendance_record_date_student_uniq'),
        ),
        migrations.RunPython(backfill_student_service_type_and_active, noop),
    ]
