# Generated by Django 4.2.7 on 2026-03-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0020_student_unique_per_session_name_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, help_text='Student/parent email (display as Email).', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_cell',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_cell',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='service_type',
            field=models.CharField(blank=True, choices=[('center_based', 'Center-based'), ('related_service', 'Related service'), ('seit', 'SEIT'), ('unknown', 'Unknown')], default='center_based', help_text='Center-based = has class; Related service / SEIT = distinct for billing; Unknown = unclassified.', max_length=20),
        ),
    ]
