# Generated by Django 4.2.7 on 2026-02-26 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_sessions', '0016_add_site_and_scope_sessions'),
        ('users', '0002_alter_user_groups_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academic_sessions.site'),
        ),
    ]
